# Generated by Django 5.2.13 on 2026-05-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название параметра')),
                ('slug', models.SlugField(max_length=100, verbose_name='URL-ключ')),
                ('param_type', models.CharField(choices=[('choice', 'Выбор из списка'), ('boolean', 'Да/Нет')], default='choice', max_length=10, verbose_name='Тип параметра')),
                ('choices', models.TextField(blank=True, help_text='Варианты через запятую, если тип "Выбор из списка"', verbose_name='Варианты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='categories.category')),
            ],
            options={
                'verbose_name': 'Параметр категории',
                'verbose_name_plural': 'Параметры категорий',
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
