# Generated by Django 5.2.13 on 2026-05-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoryparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryparameter',
            name='choices',
            field=models.TextField(blank=True, help_text='Варианты через запятую, если тип "Выбор из списка"'),
        ),
        migrations.AlterField(
            model_name='categoryparameter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='categoryparameter',
            name='param_type',
            field=models.CharField(choices=[('choice', 'Выбор из списка'), ('boolean', 'Да/Нет')], default='choice', max_length=10, verbose_name='Тип'),
        ),
    ]
