# Generated by Django 5.2.13 on 2026-05-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_categoryparameter_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryparameter',
            name='choices',
            field=models.TextField(blank=True, help_text='Варианты через запятую или с новой строки', verbose_name='Варианты'),
        ),
    ]
