# Generated by Django 5.2.13 on 2026-05-04 15:54

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.category_image_upload_to, verbose_name='Изображение категории'),
        ),
    ]
