# Generated by Django 5.2.13 on 2026-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_view',
            field=models.CharField(choices=[('grid', 'Плитки'), ('list', 'Список')], default='grid', max_length=10, verbose_name='Вид по умолчанию'),
        ),
    ]
