# Generated by Django 5.2.13 on 2026-05-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_category_default_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='view_mode',
            field=models.CharField(choices=[('grid', 'Плитки'), ('list', 'Список')], default='grid', max_length=4, verbose_name='Вид по умолчанию'),
        ),
    ]
