# Generated by Django 5.2.13 on 2026-05-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
