# Generated by Django 5.2.13 on 2026-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryparameter',
            name='mask',
            field=models.CharField(blank=True, help_text='Например: +7 (999) 999-99-99', max_length=100, verbose_name='Маска (для типа «Поле с маской»)'),
        ),
        migrations.AddField(
            model_name='categoryparameter',
            name='placeholder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подсказка в поле'),
        ),
        migrations.AlterField(
            model_name='categoryparameter',
            name='choices',
            field=models.TextField(blank=True, help_text='Варианты через запятую или с новой строки (если тип «Выбор из списка»)', verbose_name='Варианты'),
        ),
        migrations.AlterField(
            model_name='categoryparameter',
            name='param_type',
            field=models.CharField(choices=[('choice', 'Выбор из списка'), ('boolean', 'Да/Нет'), ('integer', 'Целое число'), ('float', 'Дробное число'), ('text', 'Текст'), ('mask', 'Поле с маской')], default='choice', max_length=10, verbose_name='Тип'),
        ),
    ]
