# Generated by Django 5.2.13 on 2026-05-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('person', 'Частное лицо'), ('company', 'Компания')], default='person', max_length=10, verbose_name='Тип профиля'),
        ),
    ]
