# Generated by Django 5.2.13 on 2026-05-04 15:54

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.avatar_upload_to, verbose_name='Аватар'),
        ),
    ]
