# Generated by Django 5.2.13 on 2026-05-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', help_text='ID чата для получения уведомлений в Telegram', max_length=100, verbose_name='Telegram Chat ID'),
        ),
    ]
