# Generated by Django 5.2.13 on 2026-05-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('inactive', 'Неактивно'), ('moderation', 'На модерации')], default='moderation', max_length=20, verbose_name='Статус'),
        ),
    ]
