# Generated by Django 5.2.13 on 2026-05-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('listings', '0003_alter_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='categories.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
