# Generated by Django 5.2.13 on 2026-05-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры'),
        ),
    ]
