# Generated by Django 5.2.13 on 2026-05-04 15:54

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to=apps.utils.listing_image_upload_to, verbose_name='Изображение'),
        ),
    ]
