# Generated by Django 5.2.13 on 2026-05-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
