# Generated by Django 5.2.13 on 2026-05-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Активно до'),
        ),
    ]
