# Generated by Django 5.2.13 on 2026-05-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='last_view_date',
            field=models.DateField(blank=True, null=True, verbose_name='Последний просмотр'),
        ),
        migrations.AddField(
            model_name='listing',
            name='today_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотров сегодня'),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотров всего'),
        ),
    ]
