# Generated by Django 5.2.13 on 2026-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_viewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_sticky',
            field=models.BooleanField(default=False, verbose_name='Закреплено'),
        ),
    ]
