# Generated by Django 5.2.13 on 2026-05-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_is_sticky'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Срочное'),
        ),
    ]
