# Generated by Django 5.2.13 on 2026-05-23 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0015_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_sender_deleted', models.BooleanField(default=False, verbose_name='Удалено отправителем')),
                ('is_recipient_deleted', models.BooleanField(default=False, verbose_name='Удалено получателем')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.listing', verbose_name='Объявление')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='msgs_app.message', verbose_name='Ответ на')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='msgs_app_me_recipie_625949_idx'), models.Index(fields=['sender', '-created_at'], name='msgs_app_me_sender__6d1abf_idx'), models.Index(fields=['listing', 'parent'], name='msgs_app_me_listing_c52622_idx')],
            },
        ),
    ]
